### ISSUE TITLE
`now` not working in query

### ISSUE THREAD

**Issue by sebzimmermann** [parseablehq/pb#59]
Running a query like:

```
pb query run "select * from 'otel_project-app' where ('body' like '%Transaction-ID%') LIMIT 10" --from=2024-10-24T09:22:00.52Z --to=now
```
Results in an error:
`While generating times for 'now' failed to parse duration`

**Comment by nikhilsinhaparseable** [comment]
@sebzimmermann as discussed, please use relative time like `--from=10m --to=now`
if you use a static date in from, you need to use the same for to as well
like `--from=2024-10-24T09:22:00.52Z --to=2024-10-25T00:00:00.52Z`

do update if you need any further clarification, we can close the issue otherwise
